# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24b0c4fe0ab4c09ae4c068c2edfb3c98cf70c3369b6047b446a972db0f718f3ce5a6c9c9c9c1a42384733928ee3b44000ea035e6857d5b9274d9c61e68e7f384

test:
  secret_key_base: aacad481f04b7ecaf8dad1ef6ff192a2df1075a3327756d8063474b8c6aa43d582525c6d51624704166d0a20abfc94933ba03539fd5e81d1450809cb74f1bba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
